apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediator
  template:
    metadata:
      labels:
        app: mediator
    spec:
      containers:
        - image: kapatsyndianadockerid/mediatorrr
          name: mediator
          ports:
            - containerPort: 8087
              name: mediator